# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6cb033fff46b5cd6ac2a21930ac3eba12f46da79ec04262076e4633a020510f8b53e7b10b1e49c4af778826bbe00a78416611dbf09082b2ae25dc94f7b6407d2

test:
  secret_key_base: 311dac87cc7de5ebdc21d85fb9c1b5060fc2b2fdb6196da3a1fe19827b095103400935cd54b088fcc3cd2854f415972f990bc3d5cc1aca811a5eaa6d4e451430

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
